### ISSUE TITLE
Implement loop playback

### ISSUE THREAD

**Issue by lynwilhelm** [simularium/simularium-website#298] opened 2022-01-05 23:19 UTC
## Use Case
Users want to be able to loop a simulation

## Acceptance Criteria
1. Implement looping functionality
2. Implement icon so user can turn looping on/off (off by default)
3. Implement proper tooltip styling and text
4. Update tooltip styling elsewhere in the app to be consistent with this primary tooltip style

## Details
Icon with have consistent styling and behavior as other controls with on/off state

Design Link: https://xd.adobe.com/view/75b6a3c8-f650-443b-bccc-d1fcd134a35e-20e5/screen/82c2758c-9e8a-44f5-87ab-82ef20f0ca6c/

**Comment by schoinh** [comment] 2022-01-05 23:23
Duplicate of this issue: #267

**Comment by blairlyons** [comment] 2022-01-11 20:50
> Duplicate of this issue: #267

This is the implementation issue, #267 is the UX design issue for this feature :)

**Comment by blairlyons** [comment] 2022-01-18 18:25
hold off until Lyndsay finishes placing loop button

**Comment by lynwilhelm** [comment] 2022-02-15 23:36
Issue #201 is no longer related. Decision was made that is would be better to keep record and looping icons flat and not in menu for discoverability. If ever in future we have excessive icons, we can consider moving into a menu under a button.

**Closed** 2023-06-09 22:58 UTC
Labels: blocked, quick
